### ISSUE TITLE
UPD1: Paid issue SNT

### ISSUE THREAD

**Issue by anna07test** [anna07test-org-in-SOB/anna07test-repo1-in-SOB#1]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0x6550701dd18970f831ea9e5197e9f4f12925657a](https://ropsten.etherscan.io/address/0x6550701dd18970f831ea9e5197e9f4f12925657a)
Network: Testnet (Ropsten)
Paid to: annadanchenko
