### ISSUE TITLE
REPRODUCE: paid amount is shown as 0 in Activity

### ISSUE THREAD

**Issue by anna07test** [anna07test-org-in-SOB/anna07test-repo1-in-SOB#13]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0xc04a24af0a32b4b1cd50a266cb6dcb0f625d9497](https://ropsten.etherscan.io/address/0xc04a24af0a32b4b1cd50a266cb6dcb0f625d9497)
Network: Testnet (Ropsten)
Paid to: annadanchenko
