### ISSUE TITLE
REPROMUL3: Anna 1st PR, Anton wins

### ISSUE THREAD

**Issue by anna07test** [anna07test-org-in-SOB/anna07test-repo1-in-SOB#15]

**Comment by status-open-bounty** [comment]
Balance: 0.0300 ETH
Contract address: [0x67aca612dada415460a0a90f20ed1f2d19b198ab](https://ropsten.etherscan.io/address/0x67aca612dada415460a0a90f20ed1f2d19b198ab)
Network: Testnet (Ropsten)
Paid to: antdanchenko
