### ISSUE TITLE
REPROMUL1: Anna 2nd PR, Anna wins

### ISSUE THREAD

**Issue by anna07test** [anna07test-org-in-SOB/anna07test-repo1-in-SOB#16]

**Comment by status-open-bounty** [comment]
Balance: 0.0100 ETH
Contract address: [0x7b4875947d546c3927c1ab8beaa8169a97063d36](https://ropsten.etherscan.io/address/0x7b4875947d546c3927c1ab8beaa8169a97063d36)
Network: Testnet (Ropsten)
Paid to: annadanchenko
