### ISSUE TITLE
new to claim

### ISSUE THREAD

**Issue by anna07test** [anna07test-org-in-SOB/anna07test-repo1-in-SOB#21]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0xcb504d1148762bdde4ccae779e8ec5e9c82706dc](https://ropsten.etherscan.io/address/0xcb504d1148762bdde4ccae779e8ec5e9c82706dc)
Network: Testnet (Ropsten)
Paid to: annadanchenko
