### ISSUE TITLE
UPD3: Confirm is active for the issue

### ISSUE THREAD

**Issue by anna07test** [anna07test-org-in-SOB/anna07test-repo1-in-SOB#3]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Tokens: SNT: 0.00
Contract address: [0x3645fe42b1a744ad98cc032c22472388806f86f9](https://ropsten.etherscan.io/address/0x3645fe42b1a744ad98cc032c22472388806f86f9)
Network: Testnet (Ropsten)
Paid to: annadanchenko
