### ISSUE TITLE
UPD1: Paid issue ETH

### ISSUE THREAD

**Issue by anna07test** [anna07test-org-in-SOB/anna07test-repo1-in-SOB#8]

**Comment by status-open-bounty** [comment]
Balance: 0.0000 ETH
Contract address: [0x44bf545d6c801a22174c8eaae83f3e03a5b577b0](https://ropsten.etherscan.io/address/0x44bf545d6c801a22174c8eaae83f3e03a5b577b0)
Network: Testnet (Ropsten)
Paid to: annadanchenko
